/* horus input layer [ windows ] */
#include <horus/platform/windows/input/keyboard.h>

#define PLATFORM_INPUT_KEYBOARD_KEYCODE_COUNT 256

static const keyboard_keycode_t platform_input_keyboard_keycode_mapping[PLATFORM_INPUT_KEYBOARD_KEYCODE_COUNT] = {
    KEYBOARD_KEYCODE_NONE};

static keyboard_keycode_state_t __platform_input_keyboard_keycode_states[KEYBOARD_KEYCODE_COUNT] = {
    [KEYBOARD_KEYCODE_NONE] = KEYBOARD_KEYCODE_STATE_NONE,

    /* letters */
    [KEYBOARD_KEYCODE_A] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_B] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_C] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_D] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_E] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_F] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_G] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_H] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_I] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_J] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_K] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_L] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_M] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_N] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_O] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_P] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_Q] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_R] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_S] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_T] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_U] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_V] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_W] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_X] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_Y] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_Z] = KEYBOARD_KEYCODE_STATE_NONE,

    /* numbers */
    [KEYBOARD_KEYCODE_0] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_1] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_2] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_3] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_4] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_5] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_6] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_7] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_8] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_9] = KEYBOARD_KEYCODE_STATE_NONE,

    /* general */
    [KEYBOARD_KEYCODE_TAB] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_ENTER] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_SPACE] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_ESCAPE] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_BACKSPACE] = KEYBOARD_KEYCODE_STATE_NONE,

    /* arrows */
    [KEYBOARD_KEYCODE_UP] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_DOWN] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_LEFT] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_RIGHT] = KEYBOARD_KEYCODE_STATE_NONE,

    /* modifiers */
    [KEYBOARD_KEYCODE_PRINT] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_PAGE_UP] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_LEFT_ALT] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_NUM_LOCK] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_CAPS_LOCK] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_LEFT_META] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_PAGE_DOWN] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_RIGHT_ALT] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_LEFT_SHIFT] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_LEFT_SUPER] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_RIGHT_META] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_RIGHT_SHIFT] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_RIGHT_SUPER] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_SCROLL_LOCK] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_LEFT_BRACKET] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_LEFT_CONTROL] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_RIGHT_BRACKET] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_RIGHT_CONTROL] = KEYBOARD_KEYCODE_STATE_NONE,

    /* functions */
    [KEYBOARD_KEYCODE_F1] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_F2] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_F3] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_F4] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_F5] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_F6] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_F7] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_F8] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_F9] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_F10] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_F11] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_F12] = KEYBOARD_KEYCODE_STATE_NONE,

    /* general */
    [KEYBOARD_KEYCODE_END] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_HOME] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_DELETE] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_INSERT] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_PAGEUP] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_PAGEDOWN] = KEYBOARD_KEYCODE_STATE_NONE,

    /* general */
    [KEYBOARD_KEYCODE_NUMLOCK] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_CAPSLOCK] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_SCROLLLOCK] = KEYBOARD_KEYCODE_STATE_NONE,

    /* general */
    [KEYBOARD_KEYCODE_PAUSE] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_PRINTSCREEN] = KEYBOARD_KEYCODE_STATE_NONE,

    /* symbols */
    [KEYBOARD_KEYCODE_COMMA] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_GRAVE] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_MINUS] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_SLASH] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_EQUALS] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_PERIOD] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_BACKSLASH] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_SEMICOLON] = KEYBOARD_KEYCODE_STATE_NONE,
    [KEYBOARD_KEYCODE_APOSTROPHE] = KEYBOARD_KEYCODE_STATE_NONE,
};

keyboard_keycode_t __platform_input_keyboard_keycode(/* platform_keycode_t */ u8 keycode) {
  return platform_input_keyboard_keycode_mapping[keycode];
}

b8 __platform_input_keyboard_keycode_clear_state(void) {
  for (keyboard_keycode_t keycode = KEYBOARD_KEYCODE_NONE; keycode < KEYBOARD_KEYCODE_COUNT; ++keycode) {
    if (__platform_input_keyboard_keycode_states[keycode] == KEYBOARD_KEYCODE_STATE_RELEASED) {
      __platform_input_keyboard_keycode_states[keycode] = KEYBOARD_KEYCODE_STATE_NONE;
    }
  }

  return true;
}

b8 __platform_input_keyboard_keycode_set_state(keyboard_keycode_t keycode, keyboard_keycode_state_t state) {
  if (keycode < KEYBOARD_KEYCODE_COUNT && keycode >= KEYBOARD_KEYCODE_NONE) {
    __platform_input_keyboard_keycode_states[keycode] = state;

    return true;
  }

  return false;
}

keyboard_keycode_state_t __platform_input_keyboard_keycode_state(keyboard_keycode_t keycode) {
  if (keycode < KEYBOARD_KEYCODE_COUNT && keycode >= KEYBOARD_KEYCODE_NONE) {
    return __platform_input_keyboard_keycode_states[keycode];
  }

  return KEYBOARD_KEYCODE_STATE_NONE;
}

keyboard_keycode_state_t __platform_input_keyboard_keycode_pressed_state(keyboard_keycode_t keycode) {
  keyboard_keycode_state_t previous = __platform_input_keyboard_keycode_state(keycode);

  if (previous == KEYBOARD_KEYCODE_STATE_PRESSED || previous == KEYBOARD_KEYCODE_STATE_HELD) {
    return KEYBOARD_KEYCODE_STATE_HELD;
  }

  return KEYBOARD_KEYCODE_STATE_PRESSED;
}

b8 platform_input_keyboard_keycode_is_held(keyboard_keycode_t keycode) {
  return __platform_input_keyboard_keycode_state(keycode) == KEYBOARD_KEYCODE_STATE_HELD;
}

b8 platform_input_keyboard_keycode_is_pressed(keyboard_keycode_t keycode) {
  return __platform_input_keyboard_keycode_state(keycode) == KEYBOARD_KEYCODE_STATE_PRESSED;
}

b8 platform_input_keyboard_keycode_is_released(keyboard_keycode_t keycode) {
  return __platform_input_keyboard_keycode_state(keycode) == KEYBOARD_KEYCODE_STATE_RELEASED;
}

keyboard_keycode_state_t platform_input_keyboard_keycode_state(keyboard_keycode_t keycode) {
  return __platform_input_keyboard_keycode_state(keycode);
}
